name = "elliptic_bernoulli_foundations"
version = "0.3.0"
description = "Foundations of the elliptic one-phase Bernoulli free boundary problem (variable coefficient)"
keywords = ["math"]
defaultTargets = ["EllipticBernoulli"]
preferReleaseBuild = true

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
autoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc3"

[[require]]
name = "viscosity_solns"
git = "https://github.com/willmfeldman/viscosity-solution-theory"
rev = "v0.4.0"

[[lean_lib]]
name = "EllipticBernoulli"

[[lean_lib]]
name = "EllipticBernoulliComparator"
roots = ["EllipticBernoulli.Comparator"]
