module

-- BEGIN GENERATED VOCABULARY: generated by scripts/challenge-prep.py from the Vocabulary modules; edit those, then run `python3 scripts/challenge-prep.py sync`.
public import Mathlib.Analysis.InnerProductSpace.Laplacian
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Topology.EMetricSpace.Lipschitz
public import Mathlib.LinearAlgebra.Trace
public import Mathlib.MeasureTheory.Function.LocallyIntegrable
public import Mathlib.MeasureTheory.Function.LpSeminorm.Basic
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.MeasureTheory.Measure.Haar.InnerProductSpace
public import Mathlib.MeasureTheory.Measure.Prod

@[expose] public section

-- from Vocabulary.lean
/-!
# Vocabulary: energy-decreasing perturbations (the proof of Feldman–Kim–Požár, Lemma 3.3)

Challenge vocabulary: a Mathlib-only restatement of the library files
`EllipticBernoulli/Basic/Setting.lean`, `EllipticBernoulli/Basic/Sobolev.lean`, in this order, one
part per file. Each part keeps the library's names, definitions and order, with the theorems
dropped, and keeps its `open` commands inside its own section. `scripts/challenge-prep.py sync`
copies this file into the generated block of `Challenge.lean`; Comparator checks each copied
declaration against the library by name and value.
-/


/-!
# Standing setting

The ambient space, positivity sets, free boundaries, compact containment and the divergence,
following Abedin–Feldman–Stinson. There is no global setting: statements are local, with explicit
hypotheses on `U` and `Q`.

## Conventions

* All functions are total (`E d → ℝ`); every predicate restricts to its domain explicitly, and
  values outside the domain are never used.

Restates the library file `EllipticBernoulli/Basic/Setting.lean`, with its theorems dropped. The
definitions are verbatim and in the library order, so Comparator can check that they are the
library's definitions.

## References

* F. Abedin, W. M. Feldman, K. Stinson, *Variational properties of Perron's extremal solutions in
  the Bernoulli one-phase problem*, arXiv:2609.14981.
-/

section

open Set Filter Topology
open scoped Gradient Laplacian

noncomputable section

namespace EllipticBernoulli

/-- The ambient Euclidean space `ℝᵈ`. -/
abbrev E (d : ℕ) := EuclideanSpace ℝ (Fin d)

variable {d : ℕ}

/-- The positivity set `{u > 0}` of `u` inside the domain `U` (the set `{u > 0}` of
Abedin–Feldman–Stinson, with `u` defined on `U` only). -/
def posSet (u : E d → ℝ) (U : Set (E d)) : Set (E d) := {x ∈ U | 0 < u x}

/-- The free boundary `∂{u > 0} ∩ U` (Abedin–Feldman–Stinson, (1.1) and Theorem 1.1). -/
def freeBoundary (u : E d → ℝ) (U : Set (E d)) : Set (E d) := frontier (posSet u U) ∩ U

section CompactlyContained

variable {X : Type*} [TopologicalSpace X]

/-- `A ⊂⊂ B`: the closure of `A` is compact and contained in `B`. -/
def CompactlyContained (A B : Set X) : Prop := IsCompact (closure A) ∧ closure A ⊆ B

end CompactlyContained

/-! ### Differential operators -/

/-- The divergence `∇ · ξ = tr (Dξ)` of a vector field `ξ : ℝᵈ → ℝᵈ` (pointwise, via `fderiv`;
`0` where `ξ` is not differentiable). -/
noncomputable def divergence (ξ : E d → E d) (x : E d) : ℝ :=
  LinearMap.trace ℝ (E d) (fderiv ℝ ξ x).toLinearMap

end EllipticBernoulli

end

end

/-!
# Minimal Sobolev notions and the Alt–Caffarelli energy

* `HasWeakGradient U u G`, `MemH1 U u G`, `MemH1Loc U u G` (the weak gradient is carried as
  explicit data `G`).
* `energyJ V Q u G` — the Alt–Caffarelli energy `J_Q(u; V)` (Abedin–Feldman–Stinson, (1.2)), and
  `energyJχ V Q G χ` — the energy `J(u, χ; V)` of a pair (Abedin–Feldman–Stinson, §3.4).
* `TendstoLpLoc` (strong `L^p_loc` convergence) and `TendstoWeakL2` (weak `L²` convergence).

Energies are `ℝ≥0∞`-valued lower Lebesgue integrals, so no integrability side conditions are
needed. The free boundary condition of this energy is `|∇u| = Q`; the coefficient enters squared.

Restates the library file `EllipticBernoulli/Basic/Sobolev.lean`, with its theorems dropped. The
definitions are verbatim and in the library order, so Comparator can check that they are the
library's definitions.

## References

* F. Abedin, W. M. Feldman, K. Stinson, *Variational properties of Perron's extremal solutions in
  the Bernoulli one-phase problem*, arXiv:2609.14981.
-/

section

open Set Filter Topology MeasureTheory
open scoped ENNReal ContDiff

noncomputable section

namespace EllipticBernoulli

variable {d : ℕ}

/-- `G` is a weak gradient of `u` in the open set `U`: `u` and `G` are locally
integrable on `U` and `∫_U u ∂_v φ = - ∫_U (G · v) φ` for every `φ ∈ C_c^∞(U)` and direction `v`. -/
def HasWeakGradient (U : Set (E d)) (u : E d → ℝ) (G : E d → E d) : Prop :=
  LocallyIntegrableOn u U ∧ LocallyIntegrableOn G U ∧
    ∀ φ : E d → ℝ, ContDiff ℝ ∞ φ → HasCompactSupport φ → tsupport φ ⊆ U → ∀ v : E d,
      ∫ x in U, u x * fderiv ℝ φ x v = -∫ x in U, inner ℝ (G x) v * φ x

/-- `u ∈ H¹(U)` with weak gradient `G`: `u, G ∈ L²(U)` and `G` is a weak gradient of `u` in `U`.
The weak gradient is carried as data. -/
def MemH1 (U : Set (E d)) (u : E d → ℝ) (G : E d → E d) : Prop :=
  MemLp u 2 (volume.restrict U) ∧ MemLp G 2 (volume.restrict U) ∧ HasWeakGradient U u G

/-- `u ∈ H¹_loc(U)` with weak gradient `G`: `G` is a weak gradient of `u` in `U` and
`u, G ∈ L²(K)` for every compact `K ⊆ U`. The weak gradient is carried as data. -/
def MemH1Loc (U : Set (E d)) (u : E d → ℝ) (G : E d → E d) : Prop :=
  HasWeakGradient U u G ∧ ∀ K ⊆ U, IsCompact K →
    MemLp u 2 (volume.restrict K) ∧ MemLp G 2 (volume.restrict K)

/-- The Alt–Caffarelli energy `J_Q(u; V) = ∫_V |∇u|² + Q² 1_{u>0}` (Abedin–Feldman–Stinson,
(1.2)), with the gradient supplied as data `G`. Valued in `ℝ≥0∞`. -/
noncomputable def energyJ (V : Set (E d)) (Q u : E d → ℝ) (G : E d → E d) : ℝ≥0∞ :=
  ∫⁻ x in V, ENNReal.ofReal (‖G x‖ ^ 2 + Q x ^ 2 * (posSet u V).indicator 1 x)

/-- The energy of a pair, `J(u, χ; V) = ∫_V |∇u|² + Q² χ` (Abedin–Feldman–Stinson, §3.4), with
the gradient supplied as data `G`. Valued in `ℝ≥0∞`. -/
noncomputable def energyJχ (V : Set (E d)) (Q : E d → ℝ) (G : E d → E d) (χ : E d → ℝ) :
    ℝ≥0∞ :=
  ∫⁻ x in V, ENNReal.ofReal (‖G x‖ ^ 2 + Q x ^ 2 * χ x)

section Convergence

variable {X F ι : Type*} [MeasurableSpace X] [TopologicalSpace X]

/-- Strong `L^p_loc(Ω)` convergence `f i → f₀` along `l`: `‖f i - f₀‖_{L^p(K)} → 0` for every
compact `K ⊆ Ω`. -/
def TendstoLpLoc [NormedAddCommGroup F] (p : ℝ≥0∞) (μ : Measure X) (Ω : Set X)
    (f : ι → X → F) (f₀ : X → F) (l : Filter ι) : Prop :=
  ∀ K ⊆ Ω, IsCompact K → Tendsto (fun i ↦ eLpNorm (f i - f₀) p (μ.restrict K)) l (𝓝 0)

/-- Weak `L²(Ω)` convergence `f i ⇀ f₀` along `l`: all functions are in `L²(Ω)` and
`∫_Ω ⟨f i, φ⟩ → ∫_Ω ⟨f₀, φ⟩` for every `φ ∈ L²(Ω)`. -/
def TendstoWeakL2 [NormedAddCommGroup F] [InnerProductSpace ℝ F] (μ : Measure X) (Ω : Set X)
    (f : ι → X → F) (f₀ : X → F) (l : Filter ι) : Prop :=
  (∀ i, MemLp (f i) 2 (μ.restrict Ω)) ∧ MemLp f₀ 2 (μ.restrict Ω) ∧
    ∀ φ : X → F, MemLp φ 2 (μ.restrict Ω) →
      Tendsto (fun i ↦ ∫ x in Ω, inner ℝ (f i x) (φ x) ∂μ) l
        (𝓝 (∫ x in Ω, inner ℝ (f₀ x) (φ x) ∂μ))

end Convergence

end EllipticBernoulli

end

end
-- END GENERATED VOCABULARY

/-!
# Challenge: energy-decreasing perturbations (the proof of Feldman–Kim–Požár, Lemma 3.3)

Trusted statement surface for the perturbation step in the proof of Feldman–Kim–Požár, Lemma 3.3,
together with their Lemma A.1; Abedin–Feldman–Stinson use it in the proof of their Lemma 6.3. The
statements are the key step of that proof, not the lemma itself (minimizers are viscosity
solutions), which is certified in `challenges/viscosity-minimizers`.

Let `w ≥ 0` be continuous on the open set `U`, with weak gradient `Gw`, and let a smooth `φ`
touch `w` strictly from below, or `φ₊` touch `w` strictly from above relative to
`\overline{{w > 0}}`, at a point `x₀` of an open `B ⊂⊂ U`, where the supersolution (resp.
subsolution) test of the one-phase problem `|∇u| = Q` fails. Let `Q` be Lipschitz with
`0 < c ≤ Q ≤ C` on `U`. Then for every `ρ, η > 0` a local perturbation of `w` inside
`B_ρ(x₀) ⊆ B`, trapped between `w` and `max(w, φ + η)` (resp. `min(w, (φ − η)₊)` and `w`), has
strictly smaller Alt–Caffarelli energy `J_Q(·; B) = ∫_B |∇·|² + Q² 1_{·>0}`.

The project vocabulary is restated in `Vocabulary.lean` (library files `Basic/Setting.lean`,
`Basic/Sobolev.lean`), with the library's names, definitions and order, and copied into the
generated block above by `scripts/challenge-prep.py sync`. It imports Mathlib modules only.

## References

* W. M. Feldman, I. C. Kim, N. Požár, *On the geometry of rate-independent droplet evolution*,
  Calc. Var. Partial Differential Equations 65 (2026), no. 10, Paper No. 265; arXiv:2310.03656.
  Result numbers are those of arXiv:2310.03656v2.
* F. Abedin, W. M. Feldman, K. Stinson, *Variational properties of Perron's extremal solutions in
  the Bernoulli one-phase problem*, arXiv:2609.14981.
-/

noncomputable section

open Set Filter Topology MeasureTheory Metric
open scoped ContDiff Gradient Laplacian

namespace EllipticBernoulli

variable {d : ℕ}

/-- Challenge: energy decrease when the supersolution test fails at a strict touching point
from below (proof of Feldman–Kim–Požár, Lemma 3.3). -/
theorem challenge_energy_decrease_of_not_super {U : Set (E d)} {Q w : E d → ℝ} {Gw : E d → E d}
    (hU : IsOpen U) (hQ : ∃ K, LipschitzOnWith K Q U) (hQpos : ∃ c > 0, ∀ x ∈ U, c ≤ Q x)
    (hQb : ∃ C, ∀ x ∈ U, Q x ≤ C) (hw : ContinuousOn w U) (hw0 : ∀ x ∈ U, 0 ≤ w x)
    (hGw : MemH1Loc U w Gw) {B : Set (E d)} (hB : IsOpen B) (hBU : CompactlyContained B U)
    {φ : E d → ℝ} (hφ : ContDiff ℝ ∞ φ) {x₀ : E d} (hx₀ : x₀ ∈ B)
    (htouch : φ x₀ = w x₀ ∧ ∀ᶠ y in 𝓝[≠] x₀, φ y < w y)
    (hfail : 0 < Δ φ x₀ ∧ (φ x₀ = 0 → Q x₀ < ‖∇ φ x₀‖)) :
    ∀ ρ > 0, ball x₀ ρ ⊆ B → ∀ η > 0, ∃ (w' : E d → ℝ) (Gw' : E d → E d),
      MemH1Loc U w' Gw' ∧ (∀ y ∈ U \ ball x₀ ρ, w' y = w y) ∧
      (∀ y ∈ U, w y ≤ w' y ∧ w' y ≤ max (w y) (φ y + η)) ∧
      energyJ B Q w' Gw' < energyJ B Q w Gw := by
  sorry

/-- Challenge: energy decrease when the subsolution test fails at a strict touching point
from above (proof of Feldman–Kim–Požár, Lemma 3.3). -/
theorem challenge_energy_decrease_of_not_sub {U : Set (E d)} {Q w : E d → ℝ} {Gw : E d → E d}
    (hU : IsOpen U) (hQ : ∃ K, LipschitzOnWith K Q U) (hQpos : ∃ c > 0, ∀ x ∈ U, c ≤ Q x)
    (hQb : ∃ C, ∀ x ∈ U, Q x ≤ C) (hw : ContinuousOn w U) (hw0 : ∀ x ∈ U, 0 ≤ w x)
    (hGw : MemH1Loc U w Gw) {B : Set (E d)} (hB : IsOpen B) (hBU : CompactlyContained B U)
    {φ : E d → ℝ} (hφ : ContDiff ℝ ∞ φ) {x₀ : E d} (hx₀ : x₀ ∈ B)
    (hx₀pos : x₀ ∈ closure (posSet w U))
    (htouch : max (φ x₀) 0 = w x₀ ∧
      ∀ᶠ y in 𝓝[(closure (posSet w U) ∩ U) \ {x₀}] x₀, w y < max (φ y) 0)
    (hfail : Δ φ x₀ < 0 ∧ (φ x₀ = 0 → ‖∇ φ x₀‖ < Q x₀)) :
    ∀ ρ > 0, ball x₀ ρ ⊆ B → ∀ η > 0, ∃ (w' : E d → ℝ) (Gw' : E d → E d),
      MemH1Loc U w' Gw' ∧ (∀ y ∈ U \ ball x₀ ρ, w' y = w y) ∧
      (∀ y ∈ U, min (w y) (max (φ y - η) 0) ≤ w' y ∧ w' y ≤ w y) ∧
      energyJ B Q w' Gw' < energyJ B Q w Gw := by
  sorry

end EllipticBernoulli
